#!/bin/sh 
echo "Enter the year"
read y
if [ $((y%400)) -eq 0 ]
then 
echo "the given year is leap year"
elif [ $((y%4)) -eq 0 ] 
then 
if [ $((y%100)) -eq 0 ]
then 
echo "the given year is not leap year"
else 
echo "the given year is leap year"
fi
else 
echo "the given year is not leap year"
fi
