#!/bin/bash 
read a 
read b 
read c 
echo "Enter the first number $a"
echo "Enter the second number $b"
echo "Enter the third number $c"
if [ $a -ge $b -a $a -ge $c ]
then 
echo "$a is greatest"
elif [ $b -ge $a -a $b -ge $c ]
then 
echo "$b is the greatest"
else 
echo "$c is the greatest"
fi 
