#!/bin/sh
echo "enter the base salary of the employee"
read base
da=`expr $base\*10/100|bc`
hra=`expr $base\*20/100|bc`
gross=`expr $base+$da+$hra|bc`
echo "Gross salary of employer is $gross"
